# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('skill', 'Skill'), ('approach', 'Approach')], max_length=15),
        ),
    ]
